# coding: utf-8

"""merged spec

merged spec

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""
# noqa: E501


import unittest

from ska_dlm_client.openapi.dlm_api.request_api import RequestApi


class TestRequestApi(unittest.TestCase):
    """RequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RequestApi()

    def tearDown(self) -> None:
        pass

    def test_query_data_item(self) -> None:
        """Test case for query_data_item

        Query Data Item
        """
        pass

    def test_query_deleted(self) -> None:
        """Test case for query_deleted

        Query Deleted
        """
        pass

    def test_query_exists(self) -> None:
        """Test case for query_exists

        Query Exists
        """
        pass

    def test_query_exists_and_ready(self) -> None:
        """Test case for query_exists_and_ready

        Query Exists And Ready
        """
        pass

    def test_query_expired(self) -> None:
        """Test case for query_expired

        Query Expired
        """
        pass

    def test_query_item_storage(self) -> None:
        """Test case for query_item_storage

        Query Item Storage
        """
        pass

    def test_query_new(self) -> None:
        """Test case for query_new

        Query New
        """
        pass

    def test_set_acl(self) -> None:
        """Test case for set_acl

        Set Acl
        """
        pass

    def test_set_group(self) -> None:
        """Test case for set_group

        Set Group
        """
        pass

    def test_set_metadata(self) -> None:
        """Test case for set_metadata

        Set Metadata
        """
        pass

    def test_set_oid_expiration(self) -> None:
        """Test case for set_oid_expiration

        Set Oid Expiration
        """
        pass

    def test_set_phase(self) -> None:
        """Test case for set_phase

        Set Phase
        """
        pass

    def test_set_state(self) -> None:
        """Test case for set_state

        Set State
        """
        pass

    def test_set_uid_expiration(self) -> None:
        """Test case for set_uid_expiration

        Set Uid Expiration
        """
        pass

    def test_set_uri(self) -> None:
        """Test case for set_uri

        Set Uri
        """
        pass

    def test_set_user(self) -> None:
        """Test case for set_user

        Set User
        """
        pass

    def test_update_data_item(self) -> None:
        """Test case for update_data_item

        Update Data Item
        """
        pass

    def test_update_item_tags(self) -> None:
        """Test case for update_item_tags

        Update Item Tags
        """
        pass


if __name__ == "__main__":
    unittest.main()
