# coding: utf-8

"""merged spec

merged spec

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""
# noqa: E501


import unittest

from ska_dlm_client.openapi.dlm_api.migration_api import MigrationApi


class TestMigrationApi(unittest.TestCase):
    """MigrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MigrationApi()

    def tearDown(self) -> None:
        pass

    def test_copy_data_item_migration_copy_data_item_post(self) -> None:
        """Test case for copy_data_item_migration_copy_data_item_post

        Copy Data Item
        """
        pass


if __name__ == "__main__":
    unittest.main()
