FROM python:3.12

ARG POETRY_VERSION=1.8.2
RUN apt-get update && apt-get install -y iputils-ping docker.io docker-compose &&\
    pip install pytest requests_mock docker &&\
    pip install poetry==${POETRY_VERSION} &&\
    mkdir -p /dlm &&\
    useradd -m -G docker ska-dlm &&\
    mkdir -p /home/ska-dlm/.ssh &&\
    chown -R ska-dlm:ska-dlm /home/ska-dlm &&\
    chmod 700 /home/ska-dlm/.ssh

WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.in-project true

COPY ./ ./
RUN poetry install --only main,test

ENV PATH="/app/.venv/bin:${PATH}"

ENTRYPOINT ["pytest"]
