FROM python:3.10

ARG POETRY_VERSION=1.8.2
RUN apt-get update && apt-get install -y iputils-ping docker.io docker-compose &&\
    pip install pytest requests_mock docker &&\
    pip install poetry==${POETRY_VERSION} &&\
    mkdir -p /dlm &&\
    useradd -m -G docker ska-dlm
USER ska-dlm

WORKDIR /app
# cache external dependencies
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.in-project true &&\
    poetry install --only main,test --no-root

COPY ./ ./
RUN poetry install --only main,test

ENV PATH="/app/.venv/bin:${PATH}"

ENTRYPOINT ["pytest"]
