{{- /*
This template mirrors resources/manage_keys_for_testing.sh behavior using Helm.
- For every public key file under charts/dlm-integ-env/files/keys/*pub, create a Secret named after the filename,
  with the content under the same key name.
- Create a single Secret "ssh-priv" with keys daq, pst, sdp sourced from the respective private key files.
Notes:
- These files are packaged with the chart under files/keys.
- Use stringData so Helm/Kubernetes handles base64 encoding.
*/ -}}
{{- /* Create one Secret per public key file */ -}}
{{- range $path, $f := .Files.Glob "files/keys/*pub" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ base $path }}
  labels:
    app.kubernetes.io/name: dlm-integ-env
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  {{ base $path }}: |
{{ $.Files.Get $path | nindent 4 }}
---
{{- end }}

{{- /* Create combined private keys secret */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: ssh-priv
  labels:
    app.kubernetes.io/name: dlm-integ-env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  daq: |
{{ .Files.Get "files/keys/daq-priv" | nindent 4 }}
  pst: |
{{ .Files.Get "files/keys/pst-priv" | nindent 4 }}
  sdp: |
{{ .Files.Get "files/keys/sdp-priv" | nindent 4 }}
