FROM rclone/rclone

RUN apk update && \
    apk add openssl openssh-client && \
    openssl req -x509 -nodes -days 365 \
        -subj "/C=AU/ST=WA/O=SKAO, Inc./CN=skao.int" \
        -addext "subjectAltName=DNS:skao.int" \
        -newkey rsa:2048 \
        -keyout /etc/ssl/private/selfsigned.key \
        -out /etc/ssl/certs/selfsigned.cert
