FROM python:3.10

RUN apt-get update && apt-get install -y
RUN pip install "fastapi[standard]" python-keycloak pyjwt[crypto] msal itsdangerous overrides


WORKDIR /app
RUN openssl req -x509 -newkey rsa:4096 -keyout ./key.pem -out ./cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
COPY ./gateway/dlm_gateway.py ./tests/integration/gateway/dlm_gateway.py

ARG PORT
ENV PORT=${PORT}

CMD uvicorn tests.integration.gateway.dlm_gateway:app --workers 10 --log-level warning --host 0.0.0.0 --port ${PORT}
