{{- if $.Values.integration_verification.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ska-dlm-client.fullname" . }}-integration-verification
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm-client.integration-verification.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "ska-dlm-client.integration-verification.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: integration-verification
        image: {{ .Values.directory_watcher.image}}:{{ .Values.directory_watcher.version }}
        imagePullPolicy: {{ .Values.directory_watcher.imagePullPolicy }}
        command:
        - "dlm-client-integration-verification"
        - "--directory-to-create-symlinks"
        - "{{ .Values.integration_verification.directory_to_create_symlinks }}"
        - "--directory-to-create-data-items"
        - "{{ .Values.integration_verification.directory_to_create_data_items }}"
        - "--time-between-data-item-creations"
        - "{{ .Values.integration_verification.time_between_data_item_creations }}"
        {{- if eq $.Values.integration_verification.delete_on_completion  true }}
        - "--delete-on-completion"
        - "--time-before-delete-on-completion"
        - "{{ .Values.integration_verification.time_before_delete_on_completion }}"
        {{- end }}
        volumeMounts:
        - name: dlm-configmap
          mountPath: "/home/ska-dlm/.dlm"
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: dlm-configmap
        configMap:
          name: {{ .Values.ska_dlm.fullname }}-configmap
{{- end }}
