{{- if .Values.kafka_watcher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm-client.fullname" . }}-kafka-watcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm-client.kafka-watcher.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.kafka_watcher.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.kafka_watcher.component }}
      subsystem: {{ .Values.kafka_watcher.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm-client.kafka-watcher.labels" . | indent 8 }}
    spec:
      containers:
      - name: kafka-watcher
        image: {{ .Values.ska_dlm_client.image }}:{{ .Values.ska_dlm_client.version }}
        imagePullPolicy: {{ .Values.ska_dlm_client.imagePullPolicy }}
        command:
        - "dlm-kafka-watcher"
        - "--kafka-broker-url"
        {{- if .Values.kafka_watcher.kafka_server_local }}
        - "{{ .Values.kafka.fullnameOverride }}.{{ .Release.Namespace }}:{{ .Values.kafka_watcher.kafka_server_local_port }}"
        {{- else }}
        - "{{ .Values.kafka_watcher.kafka_broker_url }}"
        {{- end }}
        - "--kafka-topic"
        - "{{ .Values.kafka_watcher.kafka_topic }}"
        - "--storage-name"
        - "{{ .Values.kafka_watcher.storage_name }}"
        - "--ingest-server-url"
        - "{{ .Values.ska_dlm_client.ingest_server_url }}"
        # Optional flag to enable rclone access check:
        {{- if .Values.kafka_watcher.check_rclone_access }}
        - "--check-rclone-access"
        {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
