{{- if $.Values.ssh_storage_access.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm-client.fullname" . }}-{{ .Values.ssh_storage_access.pst.service_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "ska-dlm-client.ssh-storage-access.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-pst-ssh
      port: 22
      targetPort: 2222
      protocol: TCP
  selector:
    component: {{ .Values.ssh_storage_access.component }}
    subsystem: {{ .Values.ssh_storage_access.subsystem }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm-client.fullname" . }}-ssh-storage-access
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm-client.ssh-storage-access.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.directory_watcher.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.ssh_storage_access.component }}
      subsystem: {{ .Values.ssh_storage_access.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm-client.ssh-storage-access.labels" . | indent 8 }}
    spec:
      {{- if .Values.ska_dlm_client.securityContext }}
      securityContext:
        {{- .Values.ska_dlm_client.securityContext | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: ssh-storage-access
          image: linuxserver/openssh-server
          ports:
            - containerPort: 2222
          env:
            - name: PUID
              value: "{{ .Values.ssh_storage_access.ssh_uid }}"
            - name: PGID
              value: "{{ .Values.ssh_storage_access.ssh_gid }}"
            - name: USER_NAME
              value: "{{ .Values.ssh_storage_access.ssh_user_name }}"
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ssh_storage_access.pst.secrets.pub_name }}
                  key: {{ .Values.ssh_storage_access.pst.secrets.pub_name }}
          volumeMounts:
            - name: ssh-config
              mountPath: /config
            - name: data-product-storage
              mountPath: /data
          {{- if eq $.Values.global.dataProduct.pvc.read_only true }}
              readOnly: true
          {{- end }}
      volumes:
        - name: ssh-config
          emptyDir: {}
        - name: data-product-storage
          persistentVolumeClaim:
            claimName: "{{ $.Values.global.dataProduct.pvc.name }}"
{{- end }}
