apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-authorized-keys
data:
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDznfuAXiSBl5vSpuqo4hI9pY7EOKVN6dkpFGeoSm0wlJ/WFDEdlqc0IUMDX4KOFQJNeuWrayIPZfB+yCFyUdTMOoGQGLD8T5f9zMQaozbT5Kt6lA/jmv+d1FqE8ftD2TSqWn4ux3lCvllDkfRA7Tv4TJNlVjhlPOF/8I566Pdo/UDFb1BopKa9kSNHKvz+rAZmrMlU3KjRgnW/WKpDG3w3kATps/FRmcr1LGgEbrsRTwwjXTrCe2YnWeiHJy6tnekK5upax5nyTM4Ftq8Xyw4ZXYJU3npd9TahSgDxX1PR4XXnMuTqWfhxuxGRO8FcAX0F4KLqwbg2Y1JgrBMrdfhl
---
apiVersion: v1
kind: Pod
metadata:
  name: ssh-server
  labels:
    app: ssh-server
spec:
  containers:
    - name: ssh
      image: linuxserver/openssh-server
      ports:
        - containerPort: 2222
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: ssh-authorized-keys
              key: authorized_keys
        - name: USER_NAME
          value: "dlm"  # optional: override default "abc"
      volumeMounts:
        - name: ssh-config
          mountPath: /config
  volumes:
    - name: ssh-config
      emptyDir: {}
