{{- if $.Values.directory_watcher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm-client.fullname" . }}-directory-watcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm-client.directory-watcher.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.directory_watcher.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.directory_watcher.component }}
      subsystem: {{ .Values.directory_watcher.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm-client.directory-watcher.labels" . | indent 8 }}
    spec:
      {{- if .Values.ska_dlm_client.securityContext }}
      securityContext:
        {{- .Values.ska_dlm_client.securityContext | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: startup-verification
        image: {{ .Values.ska_dlm_client.image}}:{{ .Values.directory_watcher.version }}
        imagePullPolicy: {{ .Values.directory_watcher.imagePullPolicy }}
        command:
        - dlm-startup-verification
        - "--storage-name"
        - {{ .Values.directory_watcher.storage_name }}
        - "--storage-root-directory"
        - {{ .Values.directory_watcher.storage_root_directory }}
        - "--ingest-server-url"
        - {{ .Values.ska_dlm_client.ingest_server_url }}
        {{- include "ska-dlm-client.readiness-probe" . | indent 8 }}
        volumeMounts:
        - name: data-product-storage
          mountPath: /data
          {{- if eq $.Values.global.dataProduct.pvc.read_only true }}
          readOnly: true
          {{- end }}
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/dlm-client-ready
          initialDelaySeconds: 10
          periodSeconds: 5
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: data-product-storage
        persistentVolumeClaim:
          claimName: "{{ $.Values.global.dataProduct.pvc.name }}"
{{- end }}
