{{- if $.Values.startup_verification.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm-client.fullname" . }}-startup-verification
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm-client.startup-verification.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.startup_verification.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.startup_verification.component }}
      subsystem: {{ .Values.startup_verification.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm-client.startup-verification.labels" . | indent 8 }}
    spec:
      {{- if .Values.ska_dlm_client.securityContext }}
      securityContext:
        {{- .Values.ska_dlm_client.securityContext | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: startup-verification
        image: {{ .Values.ska_dlm_client.image}}:{{ .Values.ska_dlm_client.version }}
        imagePullPolicy: {{ .Values.ska_dlm_client.imagePullPolicy }}
        command:
        - dlm-startup-verification
        - "--directory-to-watch"
        - {{ .Values.directory_watcher.directory_to_watch }}
        - "--storage-name"
        - {{ .Values.directory_watcher.storage_name }}
        - "--request-server-url"
        - {{ .Values.ska_dlm_client.request_server_url }}
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
