apiVersion: v1
kind: Pod
metadata:
  name: pseudo-pst-writer
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: pseudo-pst-writer
    volumeMounts:
    - name: data-product-storage
      mountPath: /data
  restartPolicy: Always
  volumes:
  - name: data-product-storage
    persistentVolumeClaim:
      claimName: shared
