---
# Default values for the SKA DLM Client.
# This is a YAML-formatted file.

auth_token: "Replace this with the authorization token"

location:
  name: "local-dev"
  type: "local-dev"
  country: "AU"
  city: "Perth"
  facility: "local"

client-config:
  target-name: "dlm-archive"
  readiness-probe-file: "~/dlm/.dlm_ready"

dir-watcher-config:
  storage:
    name: "dir-watcher"
    type: "filesystem"
    interface: "posix"
    root-dir: "~/dlm/watch_dir"
    capacity: 100000000,
    phase_level: "GAS"
  dir-updates-wait-time: 1
  status-file-filename: ~/dlm/.dlm_status
  use-status-file: false
  reload-status-file: false

configdb-watcher-config:
  storage:
    name: "sdp-watcher"
    type: "filesystem"
    interface: "posix"
    root-dir: "~/dlm/product_dir"
    capacity: 100000000,
    phase_level: "GAS"

dlm:
  polling_interval: 10 # seconds
  api-url: "http://dlm/api"
  ingest-url: "http://dlm-ingest:8001"
  request-url: "http://dlm-request:8002"
  storage-url: "http://dlm-storage:8003"
  storage_warning_percentage: 80.0
  migration-url: "http://dlm-migration:8004"
  db-url: "http://dlm-db:5432"
  rest-url: "http://dlm_postgrest:3000"
  rclone-url: "https://dlm_rclone:5572"
